In [2]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777) # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank; 몇차원 array냐
print(t.shape) # shape; array가 어떻게 생겼냐?
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


In [4]:
t = np.array([
    [1., 2., 3.], 
    [4., 5., 6.], 
    [7., 8., 9.], 
    [10., 11., 12.]
])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


In [5]:
"""
* Shape: 
* Rank:
* Axis(축): 
주어진 텐서, 매트릭스에 대해서 이 값들이 얼만가를 이해하면 편해진다.
"""

t = tf.constant([1,2,3,4]) # rank: 1, shape: 4
tf.shape(t).eval()

# Rank를 파악하는 방법은 앞의 Anchor Bracket이 몇갠지 보면 됨
# Shape은, rank가 2면 (c,d), 1이면 (?)
# 이건 가장 오른쪽에 있는 d의 경우는 각 괄호를 타고 끝까지 들어가서 element의 개수를 세면 된다.

t = tf.constant([
    [1,2],
    [3,4]
])
tf.shape(t).eval()

# t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
t = tf.constant(
    [ # axis: 0
        [ # axis: 1
            [ # axis: 2
                [1, 2, 3, 4], # axis: 3 or -1
                [5, 6, 7, 8], 
                [9, 10, 11, 12]
            ],
            [
                [13, 14, 15, 16], 
                [17, 18, 19, 20], 
                [21, 22, 23, 24]
            ]
        ]
    ]
)
tf.shape(t).eval()
# (1, 2, 3, 4)
# Rank가 4면 Axis도 4라고 보면된다.


array([1, 2, 3, 4], dtype=int32)

In [6]:
""" Matmul VS Multiply """ 
matrix01 = tf.constant([[1., 2.], [3., 4.]]) # (2, 2)
matrix02 = tf.constant([[1.], [2.]]) # (2, 1)

print("Metrix 01 shape", matrix01.shape)
print("Metrix 02 shape", matrix02.shape)

tf.matmul(matrix01, matrix02).eval()

print("-"*100)

# 주의할 것. 일반적인 곱은 matrix곱과는 결과가 다르다.. 의도적이라면 상관없긴 하지만
(matrix01*matrix02).eval()

Metrix 01 shape (2, 2)
Metrix 02 shape (2, 1)
----------------------------------------------------------------------------------------------------


array([[ 1.,  2.],
       [ 6.,  8.]], dtype=float32)

In [7]:
"""
위에서 곱이 일어난 이유,,,는
Braodcasting이란 개념 때문임
굉장히 유용하지만 잘못사용하면 독이 되는 개념이다.
""" 

# shape이 같을때 연산
matrix01 = tf.constant([[3., 3.]])
matrix02 = tf.constant([[2., 2.]])
(matrix01 + matrix02).eval()

array([[ 5.,  5.]], dtype=float32)

In [8]:
# shape이 다르더라도 연산을 해주는게 broadcasting이다
matrix01 = tf.constant([[1., 2.]])
"""
01과 02는 맞지않지만 broadcasting을 통해
[[3., 3.]]
으로 맞춰준다.
"""
matrix02 = tf.constant([[3.]])
(matrix01 + matrix02).eval() # [[(4., 5.)]]

array([[ 4.,  5.]], dtype=float32)

In [9]:
# rank가 다를때도 연산이 가능하다
matrix01 = tf.constant([[1., 2.]])
matrix02 = tf.constant([3., 4.])
(matrix01+matrix02).eval()

array([[ 4.,  6.]], dtype=float32)

In [10]:
# 아예 서로 굉장히 다른 형태로 생긴 텐서인 경우에도 앞에꺼도 extend, 뒤에꺼도 extend를 해서 계산한다.
matrix01 = tf.constant([[1., 2.]])
matrix02 = tf.constant([[3.], [4.]])
(matrix01+matrix02).eval()

array([[ 4.,  5.],
       [ 5.,  6.]], dtype=float32)

In [11]:
"""
* Reduce mean
  - 평균을 구하는데 줄여서 구하는 것.
  - 어떤 행렬에서 값이 여러개 있는데 그걸 하나로 줄여준다.
"""
tf.reduce_mean([1, 2], axis=0).eval()
# 1과 2의 평균이 1이 나온다.. 그래서 mean을 구할떄도 값이 int, float인지 구분

1

In [12]:
# 그래서 평균을 구할떈 반드시 floating number!
"""
axis 0:
아래방향

axis 1:
왼쪽에서 우측방향으로

"""
x = ([[1., 2.],
      [3., 4.]])

tf.reduce_mean(x).eval()

2.5

In [13]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [14]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [15]:
tf.reduce_mean(x, axis=-1).eval()

#  같은 reduce_mean이더라도 축에 따라 값이 달라진다.
# 축이 -1이란 것은 가장 안쪽의 값을 평균넣어라~ 가장 많이 사용하게 되겠죠..
# 축없이 하면 모든 걸 평균구하라.

array([ 1.5,  3.5], dtype=float32)

In [16]:
x = ([[1., 2.],
      [3., 4.]])

tf.reduce_sum(x).eval()

10.0

In [17]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [18]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [19]:
# 그래서 보통 많이 쓰는 것이, 제일 안쪽에 있는 축을 가지고
# 합을 낸다음에 그것을 평균내는 걸 많이 사용 했었죠??
# 그 이유를 바로 이제 알 수 있을 것임
"""!!!!"""
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [20]:
"""
* Argmax
또 많이 사용하는 것.

이것도 축의 개념과 같이 사용 가능

argmax는 맥시멈 값의 위치를 구하는 것이다.
"""

x = [[0, 1, 2],
     [2, 1, 0]]

tf.argmax(x, axis=0).eval() # 0번째 축으로 가장 큰것의 위치가 무엇이냐?
# array([1, 0, 0])

array([1, 0, 0])

In [21]:
tf.argmax(x, axis=1).eval() # 1번째 축에서 가장 큰것의 위치가 무엇이냐?
# array([2, 0])

array([2, 0])

In [22]:
tf.argmax(x, axis=-1).eval() # -1번째 축으로 가장 큰것의 위치가 무엇이냐?
# array([2, 0])

array([2, 0])

In [23]:
"""
**Reshape**
  - 가장 많이 사용!
"""

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              
              [[6, 7, 8],
               [9, 10, 11]]])

t.shape

(2, 2, 3)

In [24]:
tf.reshape(t, shape=[-1, 3]).eval() # 안에껀 3, 나머진 알아서해(-1). [-1, 3]또 이건 rank를 두개로 주는거지
# 보통 가장 안쪽의 값은 잘 안 바꾼다. 데이터가 막 섞이지는 않느다.. 바깥만 조정해서 전체를 조절

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [26]:
"""
Reshape(squeeze, expand)
"""
# 막 속에 있는 걸 squeeze해버리는거; 쫙 펴준다
tf.squeeze([[0], [1],[2]]).eval()

array([0, 1, 2], dtype=int32)

In [27]:
# dimension을 추가해주고 싶을 때
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [28]:
"""
또 뒤로가면 갈수록 많이 사용하는 건데
one_hot

어떤 인덱스값만 hot하게 만들어주는?(그자리만 1이되고 나머지는 0이되는)

어떤 주어진 숫자를 one hot으로 바꿔야하는데, 일일이 한하고 텐서플로우에 잇다.
"""
tf.one_hot([[0], [1], [2], [0]], depth=3).eval() # one_hot이 자동적으로 rank를 늘려주게된다..

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [29]:
# 그게 싫다면 one_hot후 reshape하면 됨
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [30]:
"""
Casting
도 많이 사용한다.

뭐 float으로 주어진 텐서를 integer나 
boolean로 바꾸거나(Accuracy 계산할 때, True가 많이 나온 걸 개수를 구하고 싶으면 1로 만들어서 합하면 되겟죠.)
"""

tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [31]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

In [32]:
"""
Stack도 많이 사용
"""

x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [33]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [35]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [38]:
tf.stack([x, y, z], axis=-1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [39]:
"""
ones_like
zeros_like
주어진 형태의 텐서가 있을 때, 
이거랑 모양이 똑같은 것으로 0 혹은 1로 다 들어있는 텐서를 만들고 싶을때
"""
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [40]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [42]:
"""
zip
복수개의 텐서를 가지고 있을때 
그걸 for loop같은 거로 통해서 한방에 실행시키고 싶을떄?
"""

for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)
    
print("-"*50)

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6
--------------------------------------------------
1 4 7
2 5 8
3 6 9
