In [1]:
"""
softmax function은 여러개의 class를 구별할 때 유용하다.

이것도 시작은 주어진 X에 학습할 W를 곱해서 값을 만드는 것으로 시작하는데, 
이렇게 만든 값은 단순 score에 불과하고 이걸 softmax라고 불리는 function에 통과시키면 이게 확률로 나오게된다.
"""

'\nsoftmax function은 여러개의 class를 구별할 때 유용하다.\n\n이것도 시작은 주어진 X에 학습할 W를 곱해서 값을 만드는 것으로 시작하는데, \n이렇게 만든 값은 단순 score에 불과하고 이걸 softmax라고 불리는 function에 통과시키면 이게 확률로 나오게된다.\n'

In [3]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)

In [4]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1], # 2
          [0, 0, 1], # 2
          [0, 0, 1], # 2
          [0, 1, 0], # 1
          [0, 1, 0], # 1
          [0, 1, 0], # 1
          [1, 0, 0], # 0
          [1, 0, 0]] # 0

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activation
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [6]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
    
    print('-----------')
    
    # Testing & one-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.arg_max(a, 1)))

    print('-----------')
    
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.arg_max(b, 1)))
    
    print('-----------')
    
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.arg_max(c, 1)))
    
    print('-----------')
    
    all = sess.run(hypothesis, feed_dict={
        X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]
    })
    print(all, sess.run(tf.arg_max(all, 1)))

0 5.04862
200 0.548425
400 0.432149
600 0.352467
800 0.276829
1000 0.232683
1200 0.210553
1400 0.192215
1600 0.176752
1800 0.163534
2000 0.152108
-----------
[[  1.38904958e-03   9.98601854e-01   9.06129117e-06]] [1]
-----------
[[ 0.93119204  0.06290206  0.0059059 ]] [0]
-----------
[[  1.27327668e-08   3.34112905e-04   9.99665856e-01]] [2]
-----------
[[  1.38904958e-03   9.98601854e-01   9.06129117e-06]
 [  9.31192040e-01   6.29020557e-02   5.90589503e-03]
 [  1.27327668e-08   3.34112905e-04   9.99665856e-01]] [1 0 2]
