In [5]:
import tensorflow as tf


x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# feed_dict와 같은 것으로 던져주기 위해서 placeholder를 만들어준다
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1], name='weight1'))
w2 = tf.Variable(tf.random_normal([1], name='weight2'))
w3 = tf.Variable(tf.random_normal([1], name='weight3'))
b = tf.Variable(tf.random_normal([1], name='bias'))

hypothesis = x1 * w1 + x2 + w2 + x3 * w3 + b
print("----------")
print(hypothesis)
print("----------")

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습을 시키자.
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

----------
Tensor("add_19:0", dtype=float32)
----------
0 Cost:  14225.1 
Prediction:
 [ 51.40020752  53.79545593  57.39853668  59.24330902  41.71583939]
10 Cost:  15.7829 
Prediction:
 [ 151.0785675   179.05371094  177.94700623  191.24967957  138.00915527]
20 Cost:  2.65831 
Prediction:
 [ 154.10777283  182.86061096  181.61064148  195.26116943  140.93612671]
30 Cost:  2.64584 
Prediction:
 [ 154.19967651  182.97645569  181.72200012  195.38270569  141.02555847]
40 Cost:  2.64548 
Prediction:
 [ 154.20233154  182.9801178   181.72538757  195.38604736  141.02876282]
50 Cost:  2.64513 
Prediction:
 [ 154.20225525  182.98036194  181.72549438  195.38577271  141.02934265]
60 Cost:  2.64478 
Prediction:
 [ 154.2020874   182.98049927  181.72549438  195.38540649  141.02981567]
70 Cost:  2.6444 
Prediction:
 [ 154.20193481  182.98065186  181.72547913  195.38504028  141.03031921]
80 Cost:  2.64409 
Prediction:
 [ 154.20178223  182.98075867  181.72547913  195.3846283   141.03082275]
90 Cost:  2.643

810 Cost:  2.61948 
Prediction:
 [ 154.1905365   182.99081421  181.72563171  195.35762024  141.06637573]
820 Cost:  2.61915 
Prediction:
 [ 154.19036865  182.99093628  181.72563171  195.35723877  141.06684875]
830 Cost:  2.61885 
Prediction:
 [ 154.19021606  182.99105835  181.72564697  195.35688782  141.06732178]
840 Cost:  2.61851 
Prediction:
 [ 154.19006348  182.99121094  181.72564697  195.35652161  141.0677948 ]
850 Cost:  2.61817 
Prediction:
 [ 154.18989563  182.99134827  181.72564697  195.3561554   141.06826782]
860 Cost:  2.61787 
Prediction:
 [ 154.18974304  182.99145508  181.72564697  195.35577393  141.06874084]
870 Cost:  2.61755 
Prediction:
 [ 154.18960571  182.99160767  181.72566223  195.35542297  141.06922913]
880 Cost:  2.61721 
Prediction:
 [ 154.18945312  182.99176025  181.72567749  195.35508728  141.06970215]
890 Cost:  2.6169 
Prediction:
 [ 154.1893158   182.99188232  181.72567749  195.35472107  141.07020569]
900 Cost:  2.61658 
Prediction:
 [ 154.18916321  182.992

1690 Cost:  2.59209 
Prediction:
 [ 154.17741394  183.00238037  181.7257843   195.32629395  141.10745239]
1700 Cost:  2.59182 
Prediction:
 [ 154.17729187  183.00250244  181.72579956  195.32595825  141.10792542]
1710 Cost:  2.5915 
Prediction:
 [ 154.1771698   183.00267029  181.72579956  195.32562256  141.10839844]
1720 Cost:  2.59122 
Prediction:
 [ 154.17700195  183.0027771   181.72581482  195.32527161  141.10884094]
1730 Cost:  2.59091 
Prediction:
 [ 154.17684937  183.00291443  181.72581482  195.32493591  141.10928345]
1740 Cost:  2.59061 
Prediction:
 [ 154.17671204  183.00305176  181.72581482  195.32458496  141.10975647]
1750 Cost:  2.59031 
Prediction:
 [ 154.17655945  183.00317383  181.72581482  195.32423401  141.11019897]
1760 Cost:  2.59003 
Prediction:
 [ 154.17642212  183.0032959   181.72583008  195.32389832  141.11065674]
1770 Cost:  2.5897 
Prediction:
 [ 154.17626953  183.00343323  181.72579956  195.32354736  141.1111145 ]
1780 Cost:  2.58943 
Prediction:
 [ 154.1761322 