In [1]:
import tensorflow as tf

# file을 하나만 쓸꺼니 하나로 큐를 만들었고
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

# reader를 정의하는 부분
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
# 관심있는 value를 csv로 decode하고
record_defaults = [[0.], [0.], [0.], [0.]] # 각 필드의 데이터 타입 정의
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
# xy 읽어온 것을 batch를 이용해 펌프로 빨아들이듯이 데이터를 빠는데
# x가 무엇인지,y가 무엇인지 정의 후, 몇번에 한번 펌프할때마다 10개씩 가져와라~
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) 

# placeholders for a tensor that will be always fed.
# 주의할 것은 데이터의 개수가 몇개인지,, 이 shape만 주의하면됨
X = tf.placeholder(tf.float32, shape=[None, 3]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

# shape과 맞게 해주면 됨.
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')


# 그런 다음, hypothesis, cost, optimizer 정의 한다,,
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [3]:
# 자 학습하는 과정
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)


for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) # 펌프질을 해서 데이터를 가져옴
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train],
    feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
                    "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  88557.1 
Prediction:
 [[-137.84449768]
 [-160.88571167]
 [-160.99879456]
 [-175.41572571]
 [-121.41945648]
 [ -89.01879883]
 [-132.71922302]
 [-100.52217102]
 [-149.31144714]
 [-138.00019836]]
10 Cost:  13.4065 
Prediction:
 [[ 150.07006836]
 [ 185.20925903]
 [ 179.98808289]
 [ 195.96047974]
 [ 142.53343201]
 [ 105.61273956]
 [ 145.27864075]
 [ 105.5807724 ]
 [ 174.16928101]
 [ 161.66056824]]
20 Cost:  12.7628 
Prediction:
 [[ 152.01469421]
 [ 187.53947449]
 [ 182.28735352]
 [ 198.46891785]
 [ 144.30526733]
 [ 106.92488098]
 [ 147.16470337]
 [ 106.99098206]
 [ 176.35066223]
 [ 163.6900177 ]]
30 Cost:  12.7421 
Prediction:
 [[ 152.02955627]
 [ 187.54989624]
 [ 182.30111694]
 [ 198.48814392]
 [ 144.30787659]
 [ 106.93247986]
 [ 147.1875    ]
 [ 107.01984406]
 [ 176.36387634]
 [ 163.71095276]]
40 Cost:  12.6986 
Prediction:
 [[ 152.03140259]
 [ 187.54466248]
 [ 182.29945374]
 [ 198.49055481]
 [ 144.29853821]
 [ 106.93125153]
 [ 147.19767761]
 [ 107.03931427]
 [ 176.3624115 ]
 [ 1

420 Cost:  11.1998 
Prediction:
 [[ 152.1002655 ]
 [ 187.34828186]
 [ 182.23750305]
 [ 198.57322693]
 [ 143.95544434]
 [ 106.87735748]
 [ 147.56124878]
 [ 107.73888397]
 [ 176.29762268]
 [ 163.96522522]]
430 Cost:  11.1643 
Prediction:
 [[ 152.10212708]
 [ 187.34329224]
 [ 182.23600769]
 [ 198.57528687]
 [ 143.9467926 ]
 [ 106.87582397]
 [ 147.5703125 ]
 [ 107.7563324 ]
 [ 176.29577637]
 [ 163.97103882]]
440 Cost:  11.129 
Prediction:
 [[ 152.10397339]
 [ 187.33830261]
 [ 182.23451233]
 [ 198.57733154]
 [ 143.93814087]
 [ 106.87428284]
 [ 147.5793457 ]
 [ 107.77372742]
 [ 176.29391479]
 [ 163.97680664]]
450 Cost:  11.0938 
Prediction:
 [[ 152.10585022]
 [ 187.33332825]
 [ 182.23303223]
 [ 198.57937622]
 [ 143.92951965]
 [ 106.87273407]
 [ 147.58836365]
 [ 107.79107666]
 [ 176.29206848]
 [ 163.98252869]]
460 Cost:  11.0589 
Prediction:
 [[ 152.10774231]
 [ 187.32835388]
 [ 182.23156738]
 [ 198.5814209 ]
 [ 143.92094421]
 [ 106.87119293]
 [ 147.59736633]
 [ 107.80838776]
 [ 176.29023743]

870 Cost:  9.77321 
Prediction:
 [[ 152.18589783]
 [ 187.13209534]
 [ 182.17633057]
 [ 198.66062927]
 [ 143.58406067]
 [ 106.80391693]
 [ 147.94540405]
 [ 108.4786911 ]
 [ 176.20979309]
 [ 164.19590759]]
880 Cost:  9.74514 
Prediction:
 [[ 152.18780518]
 [ 187.12747192]
 [ 182.17507935]
 [ 198.66244507]
 [ 143.57620239]
 [ 106.80219269]
 [ 147.95339966]
 [ 108.49411774]
 [ 176.2077179 ]
 [ 164.2003479 ]]
890 Cost:  9.7173 
Prediction:
 [[ 152.1897583 ]
 [ 187.12289429]
 [ 182.17388916]
 [ 198.66427612]
 [ 143.56838989]
 [ 106.8004837 ]
 [ 147.96139526]
 [ 108.50951385]
 [ 176.20568848]
 [ 164.20480347]]
900 Cost:  9.68952 
Prediction:
 [[ 152.19168091]
 [ 187.11830139]
 [ 182.1726532 ]
 [ 198.66609192]
 [ 143.56056213]
 [ 106.79875183]
 [ 147.96936035]
 [ 108.52487183]
 [ 176.20359802]
 [ 164.20921326]]
910 Cost:  9.66198 
Prediction:
 [[ 152.19361877]
 [ 187.11372375]
 [ 182.17146301]
 [ 198.66790771]
 [ 143.55279541]
 [ 106.79703522]
 [ 147.97731018]
 [ 108.54016876]
 [ 176.20155334]

1280 Cost:  8.73578 
Prediction:
 [[ 152.26542664]
 [ 186.95010376]
 [ 182.13014221]
 [ 198.73149109]
 [ 143.27619934]
 [ 106.73139191]
 [ 148.25654602]
 [ 109.07842255]
 [ 176.12330627]
 [ 164.35879517]]
1290 Cost:  8.71314 
Prediction:
 [[ 152.2673645 ]
 [ 186.9458313 ]
 [ 182.12911987]
 [ 198.73310852]
 [ 143.26904297]
 [ 106.72958374]
 [ 148.26370239]
 [ 109.09223938]
 [ 176.12115479]
 [ 164.36227417]]
1300 Cost:  8.69063 
Prediction:
 [[ 152.26931763]
 [ 186.94158936]
 [ 182.12809753]
 [ 198.73474121]
 [ 143.26190186]
 [ 106.72776794]
 [ 148.27085876]
 [ 109.10601044]
 [ 176.1190033 ]
 [ 164.36575317]]
1310 Cost:  8.66822 
Prediction:
 [[ 152.27125549]
 [ 186.93733215]
 [ 182.1270752 ]
 [ 198.7363739 ]
 [ 143.25474548]
 [ 106.72595215]
 [ 148.27796936]
 [ 109.11975098]
 [ 176.11683655]
 [ 164.36920166]]
1320 Cost:  8.64592 
Prediction:
 [[ 152.2731781 ]
 [ 186.93307495]
 [ 182.12605286]
 [ 198.73797607]
 [ 143.24761963]
 [ 106.72413635]
 [ 148.28507996]
 [ 109.13344574]
 [ 176.114

1680 Cost:  7.91612 
Prediction:
 [[ 152.34274292]
 [ 186.7857666 ]
 [ 182.09237671]
 [ 198.79345703]
 [ 143.0017395 ]
 [ 106.65799713]
 [ 148.5284729 ]
 [ 109.60294342]
 [ 176.03599548]
 [ 164.4828186 ]]
1690 Cost:  7.89772 
Prediction:
 [[ 152.34465027]
 [ 186.78179932]
 [ 182.0914917 ]
 [ 198.79490662]
 [ 142.99517822]
 [ 106.65615082]
 [ 148.53486633]
 [ 109.61534119]
 [ 176.03378296]
 [ 164.48551941]]
1700 Cost:  7.87945 
Prediction:
 [[ 152.34658813]
 [ 186.77787781]
 [ 182.09065247]
 [ 198.79638672]
 [ 142.98866272]
 [ 106.65429688]
 [ 148.54130554]
 [ 109.62771606]
 [ 176.03160095]
 [ 164.48823547]]
1710 Cost:  7.86122 
Prediction:
 [[ 152.34849548]
 [ 186.77394104]
 [ 182.08978271]
 [ 198.7978363 ]
 [ 142.98213196]
 [ 106.6524353 ]
 [ 148.54769897]
 [ 109.64006042]
 [ 176.02938843]
 [ 164.49092102]]
1720 Cost:  7.84313 
Prediction:
 [[ 152.35041809]
 [ 186.77000427]
 [ 182.08894348]
 [ 198.79928589]
 [ 142.97563171]
 [ 106.65059662]
 [ 148.55406189]
 [ 109.65235901]
 [ 176.027

In [ ]:
# Ask my score
print("Your score will be ",
     sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

print()