In [6]:
import tensorflow as tf

"""
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
"""
x_data = [[73., 80., 75.], 
          [93., 88., 93.],
          [89., 91., 90.], 
          [96., 98., 100.], 
          [73., 66., 70.]]
y_data = [
    [152.], [185.], [180.], [196.], [142.]
]

# feed_dict와 같은 것으로 던져주기 위해서 placeholder를 만들어준다
"""
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
"""
# shape에 x1,2,3까지니 우측은 3, 왼쪽은 그 데이터가 몇개냐?인데 뭐 대략적으로 n개를 가질것이다라고 말하고싶을때 None
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
"""
w1 = tf.Variable(tf.random_normal([1], name='weight1'))
w2 = tf.Variable(tf.random_normal([1], name='weight2'))
w3 = tf.Variable(tf.random_normal([1], name='weight3'))
"""

W = tf.Variable(tf.random_normal([3, 1], name='weight'))
b = tf.Variable(tf.random_normal([1], name='bias'))

"""
hypothesis = x1 * w1 + x2 + w2 + x3 * w3 + b
"""
hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습을 시키자.
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  7499.79 
Prediction:
 [[ 229.34814453]
 [ 275.99032593]
 [ 271.39294434]
 [ 297.97967529]
 [ 208.96600342]]
10 Cost:  4.59199 
Prediction:
 [[ 152.75671387]
 [ 183.94389343]
 [ 180.69248962]
 [ 199.20906067]
 [ 138.76049805]]
20 Cost:  4.50974 
Prediction:
 [[ 152.5193634 ]
 [ 183.66931152]
 [ 180.41642761]
 [ 198.90835571]
 [ 138.55380249]]
30 Cost:  4.49621 
Prediction:
 [[ 152.51304626]
 [ 183.67236328]
 [ 180.41394043]
 [ 198.90557861]
 [ 138.55885315]]
40 Cost:  4.48271 
Prediction:
 [[ 152.50746155]
 [ 183.67628479]
 [ 180.41233826]
 [ 198.9037323 ]
 [ 138.5645752 ]]
50 Cost:  4.46928 
Prediction:
 [[ 152.50186157]
 [ 183.68014526]
 [ 180.41069031]
 [ 198.90184021]
 [ 138.57025146]]
60 Cost:  4.45592 
Prediction:
 [[ 152.49629211]
 [ 183.68405151]
 [ 180.40907288]
 [ 198.8999939 ]
 [ 138.57592773]]
70 Cost:  4.44264 
Prediction:
 [[ 152.49075317]
 [ 183.68792725]
 [ 180.40745544]
 [ 198.89814758]
 [ 138.58158875]]
80 Cost:  4.42943 
Prediction:
 [[ 152.48519897]
 [ 183.6

860 Cost:  3.57762 
Prediction:
 [[ 152.09893799]
 [ 183.96195984]
 [ 180.29431152]
 [ 198.76271057]
 [ 138.98643494]]
870 Cost:  3.5687 
Prediction:
 [[ 152.09451294]
 [ 183.96504211]
 [ 180.29304504]
 [ 198.7611084 ]
 [ 138.99104309]]
880 Cost:  3.55982 
Prediction:
 [[ 152.09011841]
 [ 183.96812439]
 [ 180.29179382]
 [ 198.75953674]
 [ 138.9956665 ]]
890 Cost:  3.55098 
Prediction:
 [[ 152.08572388]
 [ 183.97120667]
 [ 180.29052734]
 [ 198.75794983]
 [ 139.0002594 ]]
900 Cost:  3.54217 
Prediction:
 [[ 152.08135986]
 [ 183.97427368]
 [ 180.28927612]
 [ 198.75637817]
 [ 139.00486755]]
910 Cost:  3.53342 
Prediction:
 [[ 152.07699585]
 [ 183.9773407 ]
 [ 180.2880249 ]
 [ 198.75480652]
 [ 139.00944519]]
920 Cost:  3.52469 
Prediction:
 [[ 152.07263184]
 [ 183.98036194]
 [ 180.28675842]
 [ 198.75320435]
 [ 139.01400757]]
930 Cost:  3.51604 
Prediction:
 [[ 152.06829834]
 [ 183.9834137 ]
 [ 180.28552246]
 [ 198.75164795]
 [ 139.01855469]]
940 Cost:  3.50742 
Prediction:
 [[ 152.06399536]

1700 Cost:  2.95955 
Prediction:
 [[ 151.76942444]
 [ 184.19346619]
 [ 180.20054626]
 [ 198.63900757]
 [ 139.33738708]]
1710 Cost:  2.95358 
Prediction:
 [[ 151.76597595]
 [ 184.19590759]
 [ 180.19955444]
 [ 198.63764954]
 [ 139.34114075]]
1720 Cost:  2.94761 
Prediction:
 [[ 151.76254272]
 [ 184.19836426]
 [ 180.1986084 ]
 [ 198.63630676]
 [ 139.34490967]]
1730 Cost:  2.94171 
Prediction:
 [[ 151.75909424]
 [ 184.20077515]
 [ 180.19763184]
 [ 198.63494873]
 [ 139.34863281]]
1740 Cost:  2.93584 
Prediction:
 [[ 151.75567627]
 [ 184.20318604]
 [ 180.19667053]
 [ 198.63360596]
 [ 139.35235596]]
1750 Cost:  2.92994 
Prediction:
 [[ 151.75224304]
 [ 184.20561218]
 [ 180.19569397]
 [ 198.63223267]
 [ 139.3560791 ]]
1760 Cost:  2.9241 
Prediction:
 [[ 151.74884033]
 [ 184.20799255]
 [ 180.19474792]
 [ 198.63087463]
 [ 139.35978699]]
1770 Cost:  2.9183 
Prediction:
 [[ 151.74543762]
 [ 184.21040344]
 [ 180.19377136]
 [ 198.62953186]
 [ 139.36347961]]
1780 Cost:  2.91252 
Prediction:
 [[ 151.7