In [7]:
import tensorflow as tf

# file을 하나만 쓸꺼니 하나로 큐를 만들었고
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

# reader를 정의하는 부분
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
# 관심있는 value를 csv로 decode하고
record_defaults = [[0.], [0.], [0.], [0.]] # 각 필드의 데이터 타입 정의
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
# xy 읽어온 것을 batch를 이용해 펌프로 빨아들이듯이 데이터를 빠는데
# x가 무엇인지,y가 무엇인지 정의 후, 몇번에 한번 펌프할때마다 10개씩 가져와라~
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) 

# placeholders for a tensor that will be always fed.
# 주의할 것은 데이터의 개수가 몇개인지,, 이 shape만 주의하면됨
X = tf.placeholder(tf.float32, shape=[None, 3]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

# shape과 맞게 해주면 됨.
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')


# 그런 다음, hypothesis, cost, optimizer 정의 한다,,
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# 자 학습하는 과정
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)


for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) # 펌프질을 해서 데이터를 가져옴
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train],
    feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
                    "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  362.293 
Prediction:
 [[ 176.72834778]
 [ 204.73268127]
 [ 205.80838013]
 [ 224.10261536]
 [ 153.99511719]
 [ 112.04479218]
 [ 169.43548584]
 [ 128.31893921]
 [ 189.23132324]
 [ 174.14028931]]
10 Cost:  24.0465 
Prediction:
 [[ 157.92825317]
 [ 182.16714478]
 [ 183.55795288]
 [ 199.87684631]
 [ 136.78730774]
 [  99.37197876]
 [ 151.30297852]
 [ 114.87759399]
 [ 168.15742493]
 [ 154.63815308]]
20 Cost:  24.1263 
Prediction:
 [[ 157.78308105]
 [ 182.02659607]
 [ 183.40138245]
 [ 199.71369934]
 [ 136.6824646 ]
 [  99.30998993]
 [ 151.18226624]
 [ 114.78907013]
 [ 168.04290771]
 [ 154.55137634]]
30 Cost:  23.9532 
Prediction:
 [[ 157.7638855 ]
 [ 182.03730774]
 [ 183.3939209 ]
 [ 199.71289062]
 [ 136.69300842]
 [  99.33300018]
 [ 151.18307495]
 [ 114.79061127]
 [ 168.06971741]
 [ 154.59541321]]
40 Cost:  23.7799 
Prediction:
 [[ 157.74560547]
 [ 182.04901123]
 [ 183.38751221]
 [ 199.7131958 ]
 [ 136.70426941]
 [  99.35649109]
 [ 151.18469238]
 [ 114.79277039]
 [ 168.09735107]
 [ 1

430 Cost:  18.0941 
Prediction:
 [[ 157.09104919]
 [ 182.4707489 ]
 [ 183.15913391]
 [ 199.72290039]
 [ 137.11296082]
 [ 100.19752502]
 [ 151.23693848]
 [ 114.85871887]
 [ 169.08744812]
 [ 156.23628235]]
440 Cost:  17.9727 
Prediction:
 [[ 157.07566833]
 [ 182.48071289]
 [ 183.15379333]
 [ 199.72309875]
 [ 137.12269592]
 [ 100.21727753]
 [ 151.23802185]
 [ 114.85999298]
 [ 169.11070251]
 [ 156.27363586]]
450 Cost:  17.8524 
Prediction:
 [[ 157.06034851]
 [ 182.49064636]
 [ 183.14849854]
 [ 199.72328186]
 [ 137.13238525]
 [ 100.23694611]
 [ 151.23910522]
 [ 114.8612442 ]
 [ 169.1338501 ]
 [ 156.31083679]]
460 Cost:  17.7332 
Prediction:
 [[ 157.04508972]
 [ 182.50053406]
 [ 183.14321899]
 [ 199.72349548]
 [ 137.14202881]
 [ 100.25653076]
 [ 151.24017334]
 [ 114.86247253]
 [ 169.15690613]
 [ 156.34785461]]
470 Cost:  17.6149 
Prediction:
 [[ 157.02990723]
 [ 182.51039124]
 [ 183.13795471]
 [ 199.72367859]
 [ 137.1516571 ]
 [ 100.27603149]
 [ 151.24121094]
 [ 114.86369324]
 [ 169.17987061

850 Cost:  13.8213 
Prediction:
 [[ 156.49824524]
 [ 182.85726929]
 [ 182.95492554]
 [ 199.72918701]
 [ 137.49214172]
 [ 100.95810699]
 [ 151.27310181]
 [ 114.89704132]
 [ 169.98291016]
 [ 157.66928101]]
860 Cost:  13.7378 
Prediction:
 [[ 156.48538208]
 [ 182.8657074 ]
 [ 182.95051575]
 [ 199.72927856]
 [ 137.50047302]
 [ 100.97459412]
 [ 151.27372742]
 [ 114.89761353]
 [ 170.00230408]
 [ 157.70021057]]
870 Cost:  13.655 
Prediction:
 [[ 156.47259521]
 [ 182.87413025]
 [ 182.94615173]
 [ 199.72940063]
 [ 137.50880432]
 [ 100.99101257]
 [ 151.27438354]
 [ 114.89816284]
 [ 170.02165222]
 [ 157.73100281]]
880 Cost:  13.5729 
Prediction:
 [[ 156.45983887]
 [ 182.88252258]
 [ 182.94178772]
 [ 199.72950745]
 [ 137.51707458]
 [ 101.00736237]
 [ 151.27502441]
 [ 114.89871216]
 [ 170.04089355]
 [ 157.76167297]]
890 Cost:  13.4916 
Prediction:
 [[ 156.4471283 ]
 [ 182.89085388]
 [ 182.93745422]
 [ 199.729599  ]
 [ 137.52531433]
 [ 101.02362823]
 [ 151.27563477]
 [ 114.89922333]
 [ 170.06005859]

1290 Cost:  10.7664 
Prediction:
 [[ 155.9810791 ]
 [ 183.19903564]
 [ 182.77932739]
 [ 199.73220825]
 [ 137.83184814]
 [ 101.62057495]
 [ 151.29364014]
 [ 114.90942383]
 [ 170.76293945]
 [ 158.90710449]]
1300 Cost:  10.71 
Prediction:
 [[ 155.97041321]
 [ 183.2061615 ]
 [ 182.77574158]
 [ 199.73225403]
 [ 137.838974  ]
 [ 101.63423157]
 [ 151.29396057]
 [ 114.90943909]
 [ 170.77903748]
 [ 158.93247986]]
1310 Cost:  10.654 
Prediction:
 [[ 155.95979309]
 [ 183.21322632]
 [ 182.77217102]
 [ 199.73228455]
 [ 137.84605408]
 [ 101.64781952]
 [ 151.29423523]
 [ 114.90943146]
 [ 170.79504395]
 [ 158.95774841]]
1320 Cost:  10.5985 
Prediction:
 [[ 155.94920349]
 [ 183.22027588]
 [ 182.76860046]
 [ 199.7322998 ]
 [ 137.85310364]
 [ 101.66136169]
 [ 151.29452515]
 [ 114.90943146]
 [ 170.81097412]
 [ 158.98292542]]
1330 Cost:  10.5435 
Prediction:
 [[ 155.93867493]
 [ 183.22729492]
 [ 182.76506042]
 [ 199.73233032]
 [ 137.8601532 ]
 [ 101.67483521]
 [ 151.2947998 ]
 [ 114.90940857]
 [ 170.826843

1700 Cost:  8.81741 
Prediction:
 [[ 155.57862854]
 [ 183.46871948]
 [ 182.64480591]
 [ 199.73254395]
 [ 138.10351562]
 [ 102.1352005 ]
 [ 151.30062866]
 [ 114.90177917]
 [ 171.36901855]
 [ 159.86019897]]
1710 Cost:  8.77822 
Prediction:
 [[ 155.56965637]
 [ 183.4747467 ]
 [ 182.64183044]
 [ 199.73251343]
 [ 138.10966492]
 [ 102.14666748]
 [ 151.30067444]
 [ 114.90139771]
 [ 171.38249207]
 [ 159.88130188]]
1720 Cost:  8.73931 
Prediction:
 [[ 155.56071472]
 [ 183.4808197 ]
 [ 182.63887024]
 [ 199.73249817]
 [ 138.11578369]
 [ 102.15808105]
 [ 151.30073547]
 [ 114.90103149]
 [ 171.39595032]
 [ 159.90235901]]
1730 Cost:  8.7008 
Prediction:
 [[ 155.55181885]
 [ 183.48681641]
 [ 182.63592529]
 [ 199.73248291]
 [ 138.12187195]
 [ 102.16944885]
 [ 151.30075073]
 [ 114.9006424 ]
 [ 171.40933228]
 [ 159.92327881]]
1740 Cost:  8.66259 
Prediction:
 [[ 155.54296875]
 [ 183.49279785]
 [ 182.63299561]
 [ 199.73245239]
 [ 138.12796021]
 [ 102.18077087]
 [ 151.30079651]
 [ 114.90023804]
 [ 171.4226

In [6]:
# Ask my score
print("Your score will be ",
     sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
     sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[ 191.81767273]]
Other scores will be  [[ 168.25297546]
 [ 177.17112732]]
